name: "Dev"

on:
  workflow_dispatch:
  push:
    branches-ignore: [master]
    paths:
      - ".github/workflows/dev.yaml"
      - ".vitepress/**"
      - "docs/**"
      - "package*.json"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: "Build"
    if: ${{ !contains(github.event.head_commit.message, '#nodev') }}
    uses: cssnr/workflows/.github/workflows/npm-build.yaml@master
    permissions:
      contents: read
    with:
      build: "npm run docs:build"
      path: ".vitepress/dist"
    secrets:
      webhook: ${{ secrets.DISCORD_WEBHOOK }}

  deploy:
    name: "Deploy"
    uses: cssnr/workflows/.github/workflows/deploy-static.yaml@master
    needs: build
    permissions:
      contents: read
    with:
      name: "dev"
      url: "https://dev-static.cssnr.com/node-badges-docs"
      path: "node-badges-docs"
      robots: true
    secrets:
      host: ${{ secrets.DEV_DEPLOY_HOST }}
      port: ${{ secrets.DEV_DEPLOY_PORT }}
      user: ${{ secrets.DEV_DEPLOY_USER }}
      pass: ${{ secrets.DEV_DEPLOY_PASS }}
      webhook: ${{ secrets.DISCORD_WEBHOOK }}
